name: CI

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Quantum Platform to use'
        required: true
        default: 'qiskit'
        type: choice
        options:
          - qiskit
          - cirq
          - braket

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create OpenQASM Directory
        run: mkdir -p openqasm

      - name: Convert Quantum Circuit to OpenQASM
        run: python quantum_converter.py
        env:
          QUANTUM_PLATFORM: ${{ github.event.inputs.platform }}

      - name: Run Tests
        run: python run_qasm.py --platform ${{ github.event.inputs.platform }}
        env:
          QUANTUM_PLATFORM: ${{ github.event.inputs.platform }}

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add openqasm/sample.qasm
          git commit -m "Update OpenQASM circuit from ${{ github.event.inputs.platform }} code" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
