name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required for pushing to the repository

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create OpenQASM Directory
        run: mkdir -p openqasm

      - name: Generate OpenQASM Circuit
        run: |
          cat > openqasm/sample.qasm << EOL
          OPENQASM 2.0;
          include "qelib1.inc";

          // Initialize quantum and classical registers
          qreg q[2];
          creg c[2];

          // Create a Bell state
          h q[0];      // Hadamard on first qubit
          cx q[0],q[1];  // CNOT with first qubit as control, second as target

          // Measure both qubits
          measure q[0] -> c[0];
          measure q[1] -> c[1];
          EOL

      - name: Commit changes
        run: |
          git add openqasm/sample.qasm
          git commit -m "Add generated OpenQASM circuit" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
